### ISSUE TITLE
Module build failed: ReferenceError: Unknown transformer u specified in optional

### ISSUE THREAD

**Issue by israelidanny** [react-bootstrap/react-router-bootstrap#94]
Alright... So, I forked + cloned this repo. Made one little adjustment (`context.router` in the new `react-router` is now an object and not a function), ran `npm run build`, did `npm link` and `npm link react-router-bootstrap` on my app.

Now, when I import the resulting package into my app, I get this bizarre error (regardless of whether I even use any of the components or code. Just the act of importing causes this):
```
[0] ../react-router-bootstrap/lib/index.js
[0] Module build failed: ReferenceError: Unknown transformer u specified in optional
[0]     at TransformerPipeline._ensureTransformerNames (/Users/danny/src/bpii-next/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:125:15)
[0]     at transformerList (/Users/danny/src/bpii-next/node_modules/babel-core/lib/babel/transformation/file/option-parsers.js:23:19)
[0]     at File.normalizeOptions (/Users/danny/src/bpii-next/node_modules/babel-core/lib/babel/transformation/file/index.js:187:31)
[0]     at new File (/Users/danny/src/bpii-next/node_modules/babel-core/lib/babel/transformation/file/index.js:145:22)
[0]     at TransformerPipeline.transform (/Users/danny/src/bpii-next/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:16)
[0]     at transpile (/Users/danny/src/bpii-next/node_modules/babel-loader/index.js:8:22)
[0]     at Object.module.exports (/Users/danny/src/bpii-next/node_modules/babel-loader/index.js:63:12)
[0]  @ ./src/components/NavBar.js 22:28-61
```

Without `react-router-bootstrap` everything looks fine and dandy. Anybody with ideas?

My app also runs `webpack` and `babel`, but doesn't crash unless I include this module.

**Comment by AlexKVal** [comment]
You need to provide reproducible steps. Without it we have nothing to work with.

--
I've checked just now:
```js
> mkdir tmp
> cd tmp
> npm istall react-router-bootstrap react-bootstrap
> touch probe.js
> <your_favorite_editor> probe.js
```
Insert this line:
```js
var react = require('react-router-bootstrap');
```
then
```js
> node probe.js
```
Everything is OK. There are no errors. :sparkle:

**Comment by israelidanny** [comment]
Well, to be extremely specific. My order of actions is as follows:
1. `git clone https://github.com/erikras/react-redux-universal-hot-example.git`
2. `npm install`
3. Elsewhere, `git clone https://github.com/react-bootstrap/react-router-bootstrap.git`
4. Edit `context.router` to be `object` and not `function` as per the new `react-router` behavior
5. `npm link` that module, and build it
6. now in the example module, `npm link react-router-bootstrap`
7. run the result & see bug...

**Comment by israelidanny** [comment]
Now - I know that this is a very specific combination, but I wonder if anybody here is experienced enough with Babel and its' quirks to give a clue as to what this error means, and why does it occur only with `react-router-bootstrap`?

Both projects use Babel (although `react-router-bootstrap` only seems to use it for building & development). But where is that `u` transformed in `react-router-bootstrap`? Why does Babel suddenly complain about it?

**Comment by AlexKVal** [comment]
Obviosly @sebmck is the most experienced with `Babel`.
Maybe he can point at least the direction :speech_balloon:

**Comment by sebmck** [comment]
Probably babel/babel#1636. Ensure that you're on the latest version.

**Comment by israelidanny** [comment]
@sebmck you my friend should be hugged for an uncomfortably long time. It worked! :)
