### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by Torwori** [react-bootstrap/react-router-bootstrap#99]
This is the error that gets thrown:

```
> react-router-bootstrap@0.17.2 prepublish /home/igor/Projects/react-router-bootstrap
> npm run build


> react-router-bootstrap@0.17.2 build /home/igor/Projects/react-router-bootstrap
> babel src --out-dir=lib && webpack && COMPRESS=1 webpack && npm run bower-prepare

src/ButtonLink.js -> lib/ButtonLink.js
src/LinkMixin.js -> lib/LinkMixin.js
src/ListGroupItemLink.js -> lib/ListGroupItemLink.js
src/MenuItemLink.js -> lib/MenuItemLink.js
src/NavItemLink.js -> lib/NavItemLink.js
src/RouterOverlayTrigger.js -> lib/RouterOverlayTrigger.js
src/index.js -> lib/index.js

assert.js:89
  throw new assert.AssertionError({
        ^
AssertionError: path must be a string
    at Module.require (module.js:364:3)
    at require (module.js:384:17)
    at module.exports (/home/igor/Projects/react-router-bootstrap/node_modules/webpack/bin/convert-argv.js:61:19)
    at Object.<anonymous> (/home/igor/Projects/react-router-bootstrap/node_modules/webpack/bin/webpack.js:54:40)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
```

Running `npm run visual-test` afterwards throws the same AssertionError.

```
node --version
v2.3.3
npm --version
2.11.3
```

**Comment by taion** [comment]
Looks like this stopped working as of webpack 0.10.2. Not sure why yet.

**Comment by taion** [comment]
ref https://github.com/webpack/webpack/issues/1280

**Comment by taion** [comment]
This got fixed with webpack upgrades.
